"""长期商业谈判世界 — 独立于 ``sotopia.envs.parallel`` 的控制逻辑与运行时。"""

from .agent_state_variables import (
    FirmAStateVariables,
    FirmBStateVariables,
    FirmCStateVariables,
    FirmDStateVariables,
    InvestorStateVariables,
    NegotiationAgentMemoryVariables,
    NegotiationPsychState,
    RegulatorStateVariables,
    firm_a_state_from_dict,
    firm_b_state_from_dict,
    firm_c_state_from_dict,
    firm_d_state_from_dict,
    investor_state_from_dict,
    negotiation_psych_state_from_role,
    psych_bundle_from_agent_dicts,
    psych_state_to_prompt_addon,
    regulator_state_from_dict,
)
from .controller import NegotiationWorldController, parse_agent_action_payload, remaining_days
from .dummy_agents import (
    NegotiationDummyPolicy,
    NegotiationDummySharedState,
    NegotiationRuleDummyAgent,
    build_rule_dummy_agents,
)
from .env import LongTermNegotiationEnv, NegotiationEpisodeActor
from .external_events import (
    ExternalEventDefinition,
    NegotiationExternalEventRunner,
    external_event_from_dict,
)
from .negotiation_metrics import (
    compute_negotiation_final_state_metrics,
    compute_negotiation_rule_metrics,
)
from .roles import (
    CANONICAL_NEGOTIATION_ROSTER,
    CANONICAL_NEGOTIATION_ROSTER_V1,
    FIRM_ROLES,
    FIRM_ROLES_ORDER,
    INSTITUTIONAL_ROLES,
    ROLE_PERSONA_EN,
    ROLE_SUMMARY_EN,
    default_agent_resources_bundle,
    validate_canonical_negotiation_roster,
)
from .session_roster import (
    CANONICAL_SESSION_ROLES,
    SessionRosterKind,
    classify_session_roster,
    roster_blocks_trade_contract_drafting,
    section7_session_hints,
)
from .types import (
    NEGOTIATION_LINEUP_FIRMS_ONLY,
    NEGOTIATION_LINEUP_WITH_INSTITUTIONAL,
    NegotiationContract,
    NegotiationTimelineParams,
    Phase,
    PRINCIPAL_PARTY_ROLES,
    ResolvedSession,
    SESSION_FIRMS_ONLY_ROLE_ORDER,
    SESSION_SPEAKER_ROLE_ORDER,
    SUPPORTED_NEGOTIATION_LINEUPS,
    SessionInviteRecord,
    SessionRuntimeMeta,
    WorldTerminalKind,
    default_financing,
    default_regulatory,
    negotiation_role_order,
)

__all__ = [
    "ExternalEventDefinition",
    "NegotiationExternalEventRunner",
    "external_event_from_dict",
    "NegotiationEpisodeActor",
    "NegotiationDummyPolicy",
    "NegotiationDummySharedState",
    "NegotiationRuleDummyAgent",
    "build_rule_dummy_agents",
    "compute_negotiation_final_state_metrics",
    "compute_negotiation_rule_metrics",
    "FirmAStateVariables",
    "FirmBStateVariables",
    "FirmCStateVariables",
    "FirmDStateVariables",
    "InvestorStateVariables",
    "RegulatorStateVariables",
    "NegotiationAgentMemoryVariables",
    "NegotiationPsychState",
    "firm_a_state_from_dict",
    "firm_b_state_from_dict",
    "firm_c_state_from_dict",
    "firm_d_state_from_dict",
    "investor_state_from_dict",
    "regulator_state_from_dict",
    "negotiation_psych_state_from_role",
    "psych_bundle_from_agent_dicts",
    "psych_state_to_prompt_addon",
    "LongTermNegotiationEnv",
    "NegotiationWorldController",
    "NegotiationTimelineParams",
    "WorldTerminalKind",
    "NegotiationContract",
    "Phase",
    "ResolvedSession",
    "SessionInviteRecord",
    "SessionRuntimeMeta",
    "SESSION_SPEAKER_ROLE_ORDER",
    "SESSION_FIRMS_ONLY_ROLE_ORDER",
    "NEGOTIATION_LINEUP_FIRMS_ONLY",
    "NEGOTIATION_LINEUP_WITH_INSTITUTIONAL",
    "SUPPORTED_NEGOTIATION_LINEUPS",
    "negotiation_role_order",
    "PRINCIPAL_PARTY_ROLES",
    "default_financing",
    "default_regulatory",
    "parse_agent_action_payload",
    "remaining_days",
    "CANONICAL_NEGOTIATION_ROSTER",
    "CANONICAL_NEGOTIATION_ROSTER_V1",
    "FIRM_ROLES",
    "FIRM_ROLES_ORDER",
    "INSTITUTIONAL_ROLES",
    "ROLE_PERSONA_EN",
    "ROLE_SUMMARY_EN",
    "default_agent_resources_bundle",
    "validate_canonical_negotiation_roster",
    "CANONICAL_SESSION_ROLES",
    "SessionRosterKind",
    "classify_session_roster",
    "roster_blocks_trade_contract_drafting",
    "section7_session_hints",
]
